name: setup-node
runs:
  using: "composite"
  steps:
    - name: Setup Node.js âš™ï¸
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - script: |
        corepack enable
        pnpm install
      displayName: pnpm install

    - name: Format code ğŸ’…
      shell: bash
      run: pnpm format:check

    - name: Lint code ğŸ§¹
      shell: bash
      run: pnpm lint